### ISSUE TITLE
No container name in docker-compose file

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/blackbox-testing#139]
Container name auto-generated and displayed like "blackbox-testing_metadata_1", if no container name in docker-compose file.

Example:
  ```
  metadata:
    image: ${coreMetadata}
    ports:
    - "48081:48081"
    hostname: edgex-core-metadata
    networks:
      edgex-network:
        aliases:
        - edgex-core-metadata
    volumes:
    - db-data:/data/db
    - log-data:/edgex/logs
    - consul-config:/consul/config
    - consul-data:/consul/data
    depends_on:
    - logging
```

Container status
```
CONTAINER ID        IMAGE                                                                 COMMAND                  CREATED             STATUS              PORTS                                                                                                            NAMES
64cc57523b86        nexus3.edgexfoundry.org:10004/docker-core-metadata-go:0.6.0           "/core-metadata --co…"   12 days ago         Up 2 hours          0.0.0.0:48081->48081/tcp, 48082/tcp                                                                              blackbox-testing_metadata_1
```
