### ISSUE TITLE
Security blackbox tests failing (aarch64)

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/blackbox-testing#369]
https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-ubuntu18.04-docker-arm64-4c-2g-master/

Log output indicates that the health checking script isn't visible to vault-worker for some reason.

```
------- vault-worker ------
creating /vault/config/assets
starting vault-worker...
/usr/local/bin/entrypoint.sh: line 34: /consul/scripts/consul-svc-healthy.sh: not found
```

Checking on the docker-compose, the volume mount appears to be there:
https://raw.githubusercontent.com/edgexfoundry/developer-scripts/master/releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml

```
  vault-worker:
    image: nexus3.edgexfoundry.org:10004/docker-edgex-security-secretstore-setup-go-arm64:master
    container_name: edgex-vault-worker
    hostname: edgex-vault-worker
    networks:
      edgex-network:
        aliases:
            - edgex-vault-worker
    volumes:
      - vault-config:/vault/config:z
      - consul-scripts:/consul/scripts:ro,z
      - /tmp/edgex/secrets/ca:/tmp/edgex/secrets/ca:ro,z
      - /tmp/edgex/secrets/edgex-kong:/tmp/edgex/secrets/edgex-kong:ro,z
    depends_on:
      - volume
      - consul
      - vault
```
